### ISSUE TITLE
本论文对drg分类为何使用多标签文本分类的模型caml

### ISSUE THREAD

**Issue by zjc982297167** [JHLiu7/EarlyDRGPrediction#8]
你好，我想请问您一下，CAML模型起初是用来进行ICD自动编码，属于多标签文本分类的问题，本论文的DRG预测按理说应该属于单标签文本分类，因为数据只有一个DRG标签，这种算是把多标签文本分类的方法应用到多标签文本分类上吗

**Comment by JHLiu7** [comment]
是的，这里只对一个而不是多个label vector做了attention-based pooling，其他和caml一样

**Comment by zjc982297167** [comment]
您好，我学习您的代码时，运行checkpoints里的model来评估测试集，得到的结果和论文里的结果很不正常，想继续请问您一下，您提供的model里的checkpoint和超参是否是最终版本呢？我按您的步骤重新训练得到的结果也偏差很大，希望您能给我提供一些帮助。

**Comment by JHLiu7** [comment]
您好，现在看主要需要改下这行

https://github.com/JHLiu7/EarlyDRGPrediction/blob/5ea0109b775e9464e635446ac59cc1c7679c6265/data_utils.py#L72

已改为
https://github.com/JHLiu7/EarlyDRGPrediction/blob/34803d2be0041007cbbbfdae0d5144dc241dfa0c/data_utils.py#L72

我还会检查一下别的代码，确认好再回复您，谢谢。

**Comment by zjc982297167** [comment]
谢谢您的回复，对我很有帮助！

**Comment by zjc982297167** [comment]
您好，想向您请教一下model文件中最后一个线性层fc，
        m = self.fc.weight.mul(m) # (N, Y, F) element-wise, final.w -> (Y,F)    
        m = m.sum(dim=2).add(self.fc.bias) # (N, Y)
这里经过注意力得分加权后的文本表示的维度为（N，Y，F），您通过以上两步操作得到最终的维度为（N，Y），第一步逐元素相乘，第二步将第三个维度求和再加上偏置，我不是很理解这两步的含义，您可以给我解释一下吗

**Comment by JHLiu7** [comment]
可以先不考虑batch维度只考虑一个sample就是(Y,F)，每个label对应一个F长度的vector，我们目的是想对它在最后一层进行线性变换，就是做一次点积再加上偏置，最后得到(Y,1)。上面的‘逐元素相乘’+‘求和’就相当于是做了点积，然后再加上bias。这样操作是为了确保我们只对每个label对应的vector进行计算。

另外我已经update了代码和checkpoints，还加上了两个cohort test set里的stay id确保和paper一致，现在应该可以得到正常结果了（可能需要重新process data），比如下面ms-drg。谢谢。

> Test Hour 24 Evaluation Results                      
dataset loaded with 1977 stays                                                       
1977 cases, 369 labels                               
MACRO-AUC       MICRO-AUC       MACRO-F1        MICRO-F1                                                  
0.8831          0.9580          0.1011          0.3003                                                    
Acc10   Acc5    Acc                                  
0.6879          0.5918          0.2979                                                                    
MAE: 1.4427  RMSE: 2.9682  Corr: 0.5576
CMI_error: -4.62%  overshot: 697  undershot: 691
